### ISSUE TITLE
Deklarovat + inicializovat proměnné až v místě použití

### ISSUE THREAD

**Issue by fan1x** [vonHimik/Sudoku#10]
např: https://github.com/vonHimik/Sudoku/blob/563f0a72f97cbc53d6b9957b5bb70833dc483f67/mainwindow.cpp#L24

Proč definovat proměnné na začátku funkce? Nemá vůbec žádný smysl tohle dělat, navíc je to nebezpečné, jelikož hrozí znovupoužívání atd...

**Comment by vonHimik** [comment]
Opraveno.
