### ISSUE TITLE
Const correctness

### ISSUE THREAD

**Issue by fan1x** [vonHimik/Sudoku#11]
Definovat parametry, které nejsou měněnné a funkce, které nic nemění jako `const`
např: https://github.com/vonHimik/Sudoku/blob/563f0a72f97cbc53d6b9957b5bb70833dc483f67/generator.cpp#L22
--> `bool Generator::CheckColumn (int x, int y , const GameMaster &gameMaster) const`

**Comment by vonHimik** [comment]
Opraveno.
