### ISSUE TITLE
Rozdelit tridy do jednotlivych souboru nejak rozumne

### ISSUE THREAD

**Issue by fan1x** [vonHimik/Sudoku#2]
Vetsinou je idealni rozdelit 1 tridu na 1 header + source file. Obcas je mozne sloucit vice spolecnych trid do jednoho souboru, pokud spolu souviseji. 
Je ale divne, kdyz je deklarace tridy v `generator.h` a definice nekde jinde.

**Comment by vonHimik** [comment]
To je přesně to, co jsem chtěl udělat, ale zároveň jsem byl konfrontován se skutečností, že dvě záhlaví jsou vzájemně propojena. A to způsobuje chybu. Připojím snímky obrazovky.

Faktem je, že chci použít objekt „GameMaster“, který bude ukládat všechny relevantní informace o herním sezení (game session), a také skrze něj můžete volat jakoukoli metodu nebo použitý objekt (tj. Generator a Solver jsou jeho součástí. Je v tomto případě možné toto všechno shromáždit pod jedním hederem?). 

Může to vypadat jako příliš komplikovaná konstrukce, ale to je ve hrách velmi běžné.

![2019-07-31_17-23-47](https://user-images.githubusercontent.com/45011438/62223850-4e47d780-b3be-11e9-8c23-de1a6083ac6b.png)
![2019-07-31_17-22-23](https://user-images.githubusercontent.com/45011438/62223851-4e47d780-b3be-11e9-942e-2387205370f6.png)

**Comment by fan1x** [comment]
Daný problém se řeší pomocí forward declaration. Zkus pogooglit (`forward declaration c++, ...`). Stačí právě správně rozdělit definici/deklaraci a už s tím nebude problém. Soubor `Generator.h` nepotřebuje includovat header `gamemaster.h`, stačí danou třídu deklarovat, protože je přistupována přes referenci, tak to bude stačit (Jde o to, že překladač musí vědět velikost všech typů a reference je vlastně pointer, což má vždy stejnou velikost, více když pogooglíš ;) )


```
#include "gamemaster.h"

class Generator {
public:
  void CheckRow(int x, int y, Gamemaster &gameMaster);
...

--->

// Generator.h
class Gamemaster;

class Generator {
public:
  void CheckRow(int x, int y, Gamemaster &gameMaster);

// Generator.cpp
#include "gamemaster.h"

void Generator::CheckRow(int x, int y, Gamemaster &gameMaster) { ... }

```

**Comment by vonHimik** [comment]
Forward declaration se problém vyřešil. Opraveno.
