### ISSUE TITLE
Proc nepouziva nejnovejsi Qt?

### ISSUE THREAD

**Issue by fan1x** [vonHimik/Sudoku#3]

**Comment by vonHimik** [comment]
Začal jsem vytvářet program v některé doporučené verzi a nechci jej aktualizovat, dokud nedokončím, aby něco není rozbité.

**Comment by fan1x** [comment]
Ok, tak to dokonči s touhle verzí. A až budou všechny problémy odstraněny (tak dej vědět) a ještě tě poprosím o aktualizaci Qt. Na 99.9% by to nemělo nic rozbít ;)

**Comment by vonHimik** [comment]
Aktualizoval jsem Qt.
