### ISSUE TITLE
Pouzivat pro cisla konstanty

### ISSUE THREAD

**Issue by fan1x** [vonHimik/Sudoku#4]
https://github.com/vonHimik/Sudoku/blob/ad726e9192e5ff0d9f8dca68c2f38f5e8bc76987/mainwindow.cpp#L43

Co je 9 -> vytvorit z toho konstantu

**Comment by vonHimik** [comment]
9 je rozměr. Sudoku má pole 9 až 9. Opraveno.

**Comment by vonHimik** [comment]
Close?

**Comment by fan1x** [comment]
To platí na všech místech v kódu, není jasné kde se dané konstatny vzaly... Obecně, skoro vždycky, když je to nějaká konstanta v kódu, jak z ní udělat pojmenovanou konstantu. Málokdy je jasné, co v Tvém kódu znamená číslo `35`

například: 
https://github.com/vonHimik/Sudoku/blob/8a60343502ea7acd345a7d0ffed0263807d1f352/solver.cpp#L50
https://github.com/vonHimik/Sudoku/blob/8a60343502ea7acd345a7d0ffed0263807d1f352/solver.cpp#L44
https://github.com/vonHimik/Sudoku/blob/8a60343502ea7acd345a7d0ffed0263807d1f352/generator.cpp#L173

**Comment by vonHimik** [comment]
Opraveno.
