### ISSUE TITLE
Nejde to udelat bez nekonecneho cyklu + break?

### ISSUE THREAD

**Issue by fan1x** [vonHimik/Sudoku#5]
https://github.com/vonHimik/Sudoku/blob/ad726e9192e5ff0d9f8dca68c2f38f5e8bc76987/mainwindow.cpp#L645

**Comment by vonHimik** [comment]
Snažil jsem se to udělat přes while a do while, funkčně to podle mého názoru vypadalo stejně, ale výsledek práce byl jiný. Ukázalo se, že se v řádcích objevují buď opakované znaky, nebo každé nové spuštění jednoduše odstraní část přidaných čísel. Přesně zjistit, kde mám chybu v tomto Qt nemůžu, on ma velmi zvláštní způsob debuggingu.

**Comment by fan1x** [comment]
Pokud se to špatně debugguje, tak použí normálně logovací hlášky `cout << "tady";`. 
Zkus tohle odladit, moc se mi to nelíbí. Je to dost ošklivý kód...

**Comment by vonHimik** [comment]
Tato metoda skutečně pomohla při ladění. Nekonečné cykly eliminovány.
