### ISSUE TITLE
Program (z drivu) po spuštění má rozbité GUI

### ISSUE THREAD

**Issue by fan1x** [vonHimik/Sudoku#6]
Zkusil jsem spustit exe soubor a program má rozbité GUI po spuštění (viz obrázek)
![error1](https://user-images.githubusercontent.com/2750870/62820581-7675ca00-bb66-11e9-968d-2579ee9fd72a.png)

**Comment by fan1x** [comment]
Můj tip je, že máš možná fixně nastavené, kde budou čáry. Ale pokud to náhodou udělá jiné okno, tak se ti to celé hne? Takže to chce udělat relativně... 
Pouze hádám :)

**Comment by vonHimik** [comment]
V mém počítači to vypadá takto:

![2019-08-20_11-15-48](https://user-images.githubusercontent.com/45011438/63330231-281db380-c33c-11e9-8cb9-3faf6f185b7f.png)

Současně se ty řádky, které jsou skutečně fixovány, u tobe zobrazují normálně (ty, které oddělují bloky). Tímto problémem se budu zabývat, zkusim pouzit ještě jiný počítač ke spuštění tohoto programu.

**Comment by vonHimik** [comment]
Je  možné reprodukovat chybu na jiném počítači.

![pctest1](https://user-images.githubusercontent.com/45011438/63340374-8a33e400-c34f-11e9-8938-89d003089a74.jpg)

**Comment by vonHimik** [comment]
Opraveno.
