### ISSUE TITLE
Může to být constexpr + size_t

### ISSUE THREAD

**Issue by fan1x** [vonHimik/Sudoku#7]
https://github.com/vonHimik/Sudoku/blob/2f769c15a415a9862ae3a244faff75683fa17a4d/mainwindow.cpp#L6

používat unsigned typy, když je to potřeba. Navíc konstanta může být constexpr

**Comment by fan1x** [comment]
Také by ta konstanta měla někam patřit. Čeho je to dimenze? Udává asi velikost pole, takže by měla být ve třídě, která obsahuje dané pole, pravděpodobně `Matrix`. 
Navíc, máš danou konstantu na více místech, to je špatně. Vytvoř jednu -> ulož ji do Matrix a používej pouze tu.
Např:
```
class Matrix {
public:
    static constexpr size_t DIMENSION = 9;
};

class GameMaster {
...
int arrayForTests[Matrix::DIMENSION, MATRIX::DIMENSION];
};
```

**Comment by vonHimik** [comment]
Opraveno.
