### ISSUE TITLE
Nefunguje ukládání do souborů

### ISSUE THREAD

**Issue by fan1x** [vonHimik/Sudoku#8]
Nefunguje ukládání do souborů (možná to ukládá někam náhodně, těžko říct). Mělo by to otevřít okno s výběrem, kam to uložit. To samé pro načítání ze souborů.

**Comment by vonHimik** [comment]
Právě bylo ukládání do disku D, ktery jsi pravděpodobně prostě neměl. Opravil jsem to, aby bylo ukládání do složky hry a testovál jsem to na různých počítačích - funguje. V případě potřeby MOHU  udelat dialogové okno pro ukládání , ale rád bych vysvětlil, proč jsem to neudělal. Úvaha o gameplayu - v případě takové malé hry je to zjevně nadbytečné a proces pouze zpomalí. Když hraji sudoku, nechci se rozhodnout, co a kde uložit. I.e. jedná se o analog fast save a fast load z „velkých“ her.

P. S. Pokud si myslís, že je to nutné, vytvořím dialogová okna pro uložení a načtení ze souboru.

**Comment by fan1x** [comment]
> Právě bylo ukládání do disku D, ktery jsi pravděpodobně prostě neměl.

Aby program náhodně někam něco ukládal, bez toho, aby to dal vědět uživateli, je prasárna!!! Prosím nedělej to!!!
Představ si, že by sis nainstaloval nějaký program třeba na přehrávání videa a ten by náhodně někam na disk něco zapisoval do složky `D:/blab`. Navíc, to ani nemáš napsané v dokumentaci....

Je ok, pokud to ukládá do složky, kde se nachází, případně nějakých známých složek pro to používaných. 

> P. S. Pokud si myslís, že je to nutné, vytvořím dialogová okna pro uložení a načtení ze souboru.

A co když si budu chtít uložit rozehranou hru a začít jinou, protože je na mě moc těžká a vrátit se k ní později a mezitím hrát jednodušší?
Prosím přidej dialogová okna, mělo by to být jednoduché ;)

**Comment by vonHimik** [comment]
Udelal jsem to.
