### ISSUE TITLE
Nějak signalizovat pokud mám špatně vyřešoné sudoku

### ISSUE THREAD

**Issue by fan1x** [vonHimik/Sudoku#9]
Pokud řeším sudoku a řekněme, že vložím číslo špatně. Potom zmačknu "solve", program ignoruje dané číslo a přepíše ho... Tady by to chtělo nějak signalizovat, aby měl uživatel šanci zjistit, že to měl špatně...

**Comment by vonHimik** [comment]
„Solve“ je poněkud odlišná feature - právě jsem si ji představil, abych ukázala hotové řešení. Podíval jsem se však na to, jak jsou hry sudoku ve službě Play Market (Android), kde se při nesprávném zadání čísla okamžitě rozsvítí. Proto jsem přidal check, když kliknu na tlačítko s číslem, a pokud je zadáno nesprávně, buňka s číslem bude zčervená.
